server:
  port: ${SERVER_PORT}
spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres
welcome:
  message: Welcome to poc project!

management:
  endpoints:
    web:
      exposure:
        exclude: "env,beans"
        include: "*"
